/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.common.controls;

import app.core.modules.constants.StoreConstants;
import app.core.systems.dtos.allcodes.AllCodeEntity;
import base.data.dal.StoreProvider;
import base.infrastructures.ComponentRunnable;
import java.util.List;

import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Khang
 */
public class AllCodeSelector extends Selector {
    /**
     * Creates new form AllCodeSelector
     */
    public AllCodeSelector() {
        super();
        initComponents();
        this._strDisplayMember="content";
        this._strValueMember="cdValue";
    }

    public void loadListByCode(String cdName){
        new Thread(new ComponentRunnable(this){       

            @Override
            public void run() {
            
                    AllCodeEntity allCode = new AllCodeEntity();
                    allCode.setCdName(cdName);
                    StoreProvider<AllCodeEntity> storeProvider = new StoreProvider(AllCodeEntity.class);
                    
                    try {
                       List<Map<String,Object>>  dataSrc=  storeProvider.executeToListMapProperties(StoreConstants.ALLCODE_LSTBYCODE, allCode);
                     ((Selector)this.getComponent()).setDataSource(dataSrc);
                     dataSrc = null;
                    } catch (Exception ex) {
                        Logger.getLogger(AllCodeSelector.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    allCode = null;
                    storeProvider = null;
                    System.gc();
                    
                
            }
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
