/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.common.controls;

import base.guis.controls.BaseComponent;
import java.sql.Date;
import java.time.LocalDate;
import java.util.Calendar;
import org.jdesktop.swingx.JXDatePicker;
import ultilities.factories.DateTimeFactory;

/**
 *
 * @author Khang
 */
public class DatePickerControl extends BaseComponent {

    /**
     * Creates new form DatePickerControl
     */
    public DatePickerControl() {
        initComponents();
       
        this.jXDatePicker1.setFormats(DateTimeFactory.Instance().getDateFormatter());
    }

    public JXDatePicker getDatePicker() {
        return this.jXDatePicker1;
    }

    public Date getValue() {
       java.util.Date selectedDate = getDatePicker().getDate();
        if (selectedDate == null) {
            return this.getMinDate();
        }
        
        //getDatePicker().getEditor().isEditValid()

        return new Date(selectedDate.getTime());
    }

    public void setValue(Date date) {
        if (date == null || date != null && DateTimeFactory.Instance().isMinDate(date)) {
            this.getDatePicker().setDate(null);
            return;
        }
        this.getDatePicker().setDate(date);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
