/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.common.controls;

import base.guis.controls.core.BaseFormattedField;
import java.text.ParseException;
import ultilities.helpers.FormatHelper;


/**
 *
 * @author Khang
 */
public class DecimalInput extends BaseFormattedField  {
    /**
     * Creates new form MoneyInput
     */
    boolean isNegative = false;
    
    public DecimalInput() throws ParseException {
        super(FormatHelper.getCurrencyFormat());
        initComponents();
        this.setText("0");      
        
      }
           
    public boolean getIsNegative(){
        return this.isNegative;
    }
    public void setIsNegative(boolean isNegative){
        this.isNegative=isNegative;
    }



   
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
