/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.common.controls;

import base.configurations.constants.AppStringConstants;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Khang
 */
public class GroupBox extends javax.swing.JPanel {

    /**
     * Creates new form GroupBox
     */
    TitledBorder titleBorder;
    String strPreTitle = AppStringConstants.GROUP_BOX_PRETITLE;    
    String strTitleName = "";
    String strEditStatus = "";
    String strFullTitle = "";
    public GroupBox() {
        initComponents();
        //titleBorder = BorderFactory.createTitledBorder(strTitleName); 
        //this.setBorder(null);
        //this.setBorder(titleBorder);
     
    }

    public void setTittle(String title){
        StringBuilder sb = new StringBuilder();
        sb.append(strPreTitle).append(" ").append(title.toUpperCase());
        this.strTitleName = sb.toString();
        this.strFullTitle = this.strTitleName;
        setTitleBorderBox(strFullTitle);
        sb = null;
        System.gc();
    }
    
    public void setEditStatusTitle(String title){
        StringBuilder sb = new StringBuilder();
        sb.append(strTitleName).append(" | ").append(title);
        this.strFullTitle = sb.toString();
        setTitleBorderBox(strFullTitle);
        sb = null;
        System.gc();
    }
    
    private void setTitleBorderBox(String title){
        this.setBorder(null);
        this.setBorder(BorderFactory.createTitledBorder(title));
        System.gc();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
