/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.core.systems.guis.allcodes;

import app.core.modules.constants.StoreConstants;
import app.core.systems.dtos.allcodes.AllCodeDisplayDto;
import app.core.systems.dtos.allcodes.AllCodeEntity;
import base.applications.imps.BaseService;
import base.guis.controls.BaseEditPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khang
 */
public class AllCodeGUI extends BaseEditPanel {

    /**
     * Creates new form AllCodeGUI
     */
    public AllCodeGUI() {
        super(new AllCodeEntity(),new AllCodeEntity(),new AllCodeDisplayDto());
        initComponents();
        init();
    }

    private void init(){
        this.appService = new BaseService(AllCodeEntity.class, AllCodeDisplayDto.class);

        dataTable1.setEditPanel(this);
        
        this.tableModel = (DefaultTableModel) dataTable1.getTable().getModel();
         setTableColumns();
        this.dataTable1.setEnableRowClick(false);
        
         // set store procedure names
        this.setStoreProcedureNames(
                StoreConstants.ALLCODE_SEARCH,
                StoreConstants.ALLCODE_INSORUPD,
                StoreConstants.ALLCODE_BYID);
        
        this.dataTable1.onResetSearch();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dataTable1 = new app.common.controls.DataTable();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN TRƯỜNG GIAO DỊCH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(dataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.common.controls.DataTable dataTable1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setTableColumns() {
         String[] headers = new String[]{
            //0     1       2           3       4       5           6
            "STT", "Tên trường", "Nội dung", "Phân hệ"};
        tableModel.setColumnIdentifiers(headers);

//        TableColumnModel colModel = dataTable1.getTable().getColumnModel();
//       
//        //format cho các cột
//        colModel.getColumn(4).setCellRenderer(NumberRendererHelper.getCurrencyRenderer());
//        colModel.getColumn(6).setCellRenderer(FormatRenderHelper.getDateRenderer());
    }

    @Override
    public void bindingModelToView() {
    }

    @Override
    public void bindingViewToModel() {
    }
}
