/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.core.trade.guis.productCategories;

import app.core.modules.constants.StoreConstants;
import app.core.trade.dtos.productCategories.ProductCategoryDisplayDto;
import app.core.trade.dtos.productCategories.ProductCategoryEntity;
import base.applications.imps.BaseService;
import base.guis.controls.BaseEditPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import ultilities.helpers.FormatRenderHelper;
import ultilities.helpers.NumberRendererHelper;
import ultilities.utils.MathUtils;

/**
 *
 * @author Khang
 */
public class ProductCategoryGUI extends BaseEditPanel {

    /**
     * Creates new form ProductCategoryCategoryGUI
     */
     public ProductCategoryGUI() throws InstantiationException, IllegalAccessException {     
        //current obj, search obj, display obj
        super(new ProductCategoryEntity(),new ProductCategoryEntity(),new ProductCategoryDisplayDto());  
        initComponents();       
        init();
    }
    private void init() throws InstantiationException, IllegalAccessException{
        this.appService = new BaseService(ProductCategoryEntity.class,ProductCategoryDisplayDto.class);
        dataTable.setEditPanel(this);             
       
        this.tableModel = (DefaultTableModel) dataTable.getTable().getModel();   
        this.appCrudToolBar.setEditPanelUI(this);
        this.setGroupInformation(this.groupInformation);
        setTableColumns();
        
        // set store procedure names
        this.setStoreProcedureNames(
                StoreConstants.PRODUCTCATEGORY_SEARCH(),
                StoreConstants.PRODUCT_INSORUPD(),
                StoreConstants.PRODUCT_BYID());
        
        this.dataTable.onResetSearch();
    }
    
    @Override
    public void setTableColumns() {
                
        String[] headers = new String[]{"STT","Id","Tên loại","Diễn giải"};
        tableModel.setColumnIdentifiers(headers); 
      
        TableColumnModel colModel = dataTable.getTable().getColumnModel();      
        
    }

        @Override
    public void bindingModelToView( ) {
        //System.out.println(txtPrice.getValue());
       // ProductCategoryEntity obj = (ProductCategoryEntity) this.getCurrentObj();
      
    }

    @Override
    public void bindingViewToModel() {
      ProductCategoryEntity entity = (ProductCategoryEntity) this.getCurrentObj();
      
     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataTable = new app.common.controls.DataTable();
        groupInformation = new app.common.controls.GroupBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        appCrudToolBar = new app.common.controls.AppCrudToolBar();

        jTextField1.setText("jTextField1");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout groupInformationLayout = new javax.swing.GroupLayout(groupInformation);
        groupInformation.setLayout(groupInformationLayout);
        groupInformationLayout.setHorizontalGroup(
            groupInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupInformationLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        groupInformationLayout.setVerticalGroup(
            groupInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupInformationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(groupInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(appCrudToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appCrudToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(dataTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.common.controls.AppCrudToolBar appCrudToolBar;
    private app.common.controls.DataTable dataTable;
    private app.common.controls.GroupBox groupInformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
