/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.mains.guis.logins;

import app.core.systems.dtos.users.UserEntity;
import app.mains.navigations.AppNavigator;
import base.configurations.constants.SystemConstants;
import base.configurations.constants.SystemStringConstants;
import base.infrastructures.systems.AppContext;
import base.ultilities.utils.MessageUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;

/**
 *
 * @author Khang
 */
public class LoginFrame extends javax.swing.JFrame implements ActionListener, KeyListener  {

    /**
     * Creates new form LoginFrame
     */
    AppNavigator appNavigator;

    public LoginFrame(AppNavigator appNavigator) {
        this.appNavigator = appNavigator;
        initComponents();
        init();
    }

    private void init() {
        this.setTitle("MainWindow");
        //this.setContentPane(loginGUI1);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setBounds(SystemConstants.CENTER_POSX, SystemConstants.CENTER_POSY,
                SystemConstants.DEFAULT_SCREEN_WIDTH, SystemConstants.DEFAULT_SCREEN_HEIGHT);

        this.loginGUI1.getButtonSignIn().addActionListener(this);
        this.getRootPane().setDefaultButton(this.loginGUI1.getButtonSignIn());
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        onSubmit();
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
           onSubmit();
        }

    }

    private void onSubmit() {
        UserEntity user = appNavigator.getUserSignIn(this.loginGUI1.getTxtUserName().getText(),
                new String(this.loginGUI1.getTxtPasswordField().getPassword()));

        if (user == null || user != null && user.getId() == 0) {
            MessageUtils.showErrorMessage(this, SystemStringConstants.STR_ERROR_LOGIN);
        } else {
            AppContext.getInstance().setCurrentUser(user);
            appNavigator.setAuthenticationScreen();
            this.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginGUI1 = new app.mains.guis.logins.LoginGUI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.mains.guis.logins.LoginGUI loginGUI1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
