/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package base.guis.controls.core;

import base.configurations.constants.ColorConstants;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Khang
 */
public class TableCustom extends javax.swing.JTable {

    boolean isDisableEdit = true;
    /** Creates new form TableCustom */
    public TableCustom() {
        initComponents();
       this.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
       this.getTableHeader().setOpaque(false);
       this.setSelectionBackground(Color.decode(ColorConstants.SILVER_LIGHT));
       this.setSelectionForeground(Color.decode(ColorConstants.BLACK));
       this.getTableHeader().setForeground(Color.WHITE);
       this.getTableHeader().setBackground(Color.decode(ColorConstants.TABLE_HEADER_BACKGROUND));
       
       this.setRowHeight(28);
       this.setFillsViewportHeight(true);
       this.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
        
    }

    @Override
    public boolean isCellEditable(int row, int column) {     
        if(!isDisableEdit){
            return super.isCellEditable(row, column);
        }       
        return false;               
    };
    
    public void setDisableEdit(boolean isDisableEdit){
        this.isDisableEdit = isDisableEdit;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
