/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.common.appControls.productModals;

import app.common.interfaces.modals.IModalEvent;
import app.core.modules.constants.PageConstants;
import app.core.trade.dtos.products.ProductEntity;
import app.core.trade.guis.products.ProductListComponent;
import app.mains.MainWindow;
import base.configurations.constants.SystemConstants;
import base.guis.controls.BaseFrame;
import base.guis.controls.BaseModal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JDialog;

/**
 *
 * @author Khang
 */
public class ProductListModal extends BaseFrame implements ActionListener {

    /**
     * Creates new form ProductListModal
     */
    IModalEvent modalEvent;

    public ProductListModal(IModalEvent modalEvent) {
        super();
        initComponents();
        this.modalEvent = modalEvent;
        init();
    }

    private void init() {

        this.add(productListComponent1);
        this.setTitle(PageConstants.PRODUCT_INFO);

        this.setBounds(SystemConstants.CENTER_POSX + 15,
                SystemConstants.CENTER_POSY + 15, 550, 750);
        this.setVisible(false);

        productListComponent1.getBtnSelect().addActionListener(this);
    }

    public ProductListComponent getProductListComponent() {
        return this.productListComponent1;
    }

    public List<ProductEntity> getSelectedItems() {
        return this.getProductListComponent().getSelectedItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productListComponent1 = new app.core.trade.guis.products.ProductListComponent();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productListComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productListComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        if (this.modalEvent != null) {
            if (e.getSource() == this.getProductListComponent().getBtnSelect()) {
                modalEvent.onGetItems();
            }
        }
        this.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.core.trade.guis.products.ProductListComponent productListComponent1;
    // End of variables declaration//GEN-END:variables
}
