/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.core.systems.guis.roles;

import app.common.modules.constants.StoreConstants;
import app.core.systems.dtos.roles.RoleDisplayDto;
import app.core.systems.dtos.roles.RoleEntity;

import base.applications.imps.BaseService;
import base.guis.controls.BaseEditPanel;
import base.ultilities.helpers.FormatRenderHelper;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Khang
 */
public class RoleGUI extends BaseEditPanel {

    /**
     * Creates new form RoleGUI
     */
    public RoleGUI() {
         super(new RoleEntity(),new RoleEntity(),new RoleDisplayDto());
        initComponents();
        init();
    }
  private void init(){
        this.appService = new BaseService(RoleEntity.class, RoleDisplayDto.class);

        dataTable1.setEditPanel(this);
        
        this.tableModel = (DefaultTableModel) dataTable1.getTable().getModel();
         setTableColumns();
        this.dataTable1.setEnableRowClick(false);
        
         // set store procedure names
        this.setStoreProcedureNames(
                StoreConstants.ROLE_SEARCH,
                StoreConstants.ROLE_INSORUPD,
                StoreConstants.ROLE_BYID);
        
        this.dataTable1.onResetSearch();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataTable1 = new app.common.controls.DataTable();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN QUYỀN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        @Override
    public void setTableColumns() {
         String[] headers = new String[]{
            //0         1       2               3             4       5           6
            "STT", "Mã quyền", "Tên quyền", "Ngày tạo","Người tạo"};
        tableModel.setColumnIdentifiers(headers);

        TableColumnModel colModel = dataTable1.getTable().getColumnModel();
       
        //format cho các cột
        colModel.getColumn(3).setCellRenderer(FormatRenderHelper.getDateRenderer());
    }

    @Override
    public void bindingModelToView() {
    }

    @Override
    public void bindingViewToModel() {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.common.controls.DataTable dataTable1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
